#This is a automatic dispatcher which should be copied into eks branches it is not intended to be triggered from main

name: Build and Deploy ONIX Service

on:
  push:
    branches:
      - "draft-*"

jobs:
  deploy:
    uses: ONDC-Official/automation-specifications/.github/workflows/_onix-deploy-reusable.yml@main
    permissions:
      contents: read
      packages: write
    with:
      source_ref: ${{ github.sha }}
      deploy_values_file: k8/aws/helm/domain-layer/values.yaml
    secrets:
      db_api_key: ${{ secrets.EKS_DB_SERVICE_API_KEY }}
      db_api_base_url: ${{ secrets.EKS_DB_SERVICE_BASE_URL }}
      redis_password: ${{ secrets.REDIS_PASSWORD }}
      iac_repo_pat: ${{ secrets.IAC_REPO_PAT }}
